SELECT

IR1.TCU_RUC_CUMPLIMIENTO CONTRIBuyente
,cast(IR1.TCU_PERIODO_DEC as varchar) PERIODO
,IR1.TCU_TIP_DECLARACION TIPO_DECLARACION
,IR1.TCU_TIP_DOCUMENTO TIPO_DOCUMENTO
,ltrim(str(IR1.TCU_NUM_DECLARACION ,30)) NUM_DECLARACION  
,ltrim(str(IR1.TCU_DECLARACION_SUST,30)) NUM_DECLARACION_SUST
,cast(IR1.TCU_FEC_CUMPLIMIENTO as date)FC_DECLARACION
,D.VIA_DECLARACION VIA_ENVIO
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.INVENTARIO_INICIAL WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.INVENTARIO_INICIAL END [Inventario inicial]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.COMPRAS_LOCALES WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.COMPRAS_LOCALES END [Compras locales]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.COMPRAS_EXTERIOR WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.COMPRAS_EXTERIOR END [Compras exterior]
,IRB.ITBIS_LLEVADO_AL_COSTO  [ITBIS llevado al costo]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.INVENTARIO_FINAL WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.INVENTARIO_FINAL END [Inventario Final]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.COSTO_VENTA WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.COSTO_VENTA END [Total de costo de venta]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.SUELDOS_SALARIOS WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.SUELDO_SALARIOS END [Sueldos y Salarios]
,IRB.RETRIBUCIONES_COMPLEMENTARIAS [Retribuciones Complementarias]
,IRB.SEGUROS [Seguros]
,CASE WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.APORTE_TSS END [Aporte TSS]
,IRB.APORTE_INFOTEP [Aporte Infotep],
IRB.OTROS_GASTOS_PERSONAL [Otros Gastos de Personal],
IRB.TOTAL_GASTOS_PERSONAL [Total de gastos de personal],
IRB._HONORARIOS_SERVICIOS_PROFESIONALES [Gastos Honorarios por servicios profesionales],
IRB.HONORARIOS_SERVICIOS_EXTERIOR_392 [Gastos Honorarios por servicios del exterior (392-07)], 
IRB.HONORARIOS_SERVICIOS_EXTERIOR_PFJ [Gastos Honorarios por servicios del exterior (Personas fiscas y Morales)]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.FACTURA_ELECTRICAS WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.FACTURAS_ELECTRICAS END  [Gastos de facturas eléctricas]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.FACTURA_TELEFONICA WHEN IR1.TCU_PERIODO_DEC >=201712 THEN  IRB.FACTURAS_TELEFONICAS END [Gastos de facturas telefónicas]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.GASTOS_COMBUSTIBLE WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.SUMINISTRO_COMBUSTIBLE  END [Gastos Suministro de combustible],
IRB.SEGURIDAD_MESAJERIA_TRANSPORTE [Gastos por seguridad, mensajería, transporte y otros servicios],
IRB.OTROS_TRABAJOS_SUMINISTRO_SERVICIOS [Otros gastos por trabajo, suministro y servicios],
IRB.TOTAL_TRABAJO_SUMINISTRO_SERVICIO [Total de gastos por trabajo, suministro y servicios]
,CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.ARRENDAMIENTO WHEN IR1.TCU_PERIODO_DEC >=201712 THEN IRB.ARRENDAMIENTO END [Gastos de arrendamiento]
,IRB.DEPRECIACION_ACTIVOS_FIJOS1 [Gastos de depreciación de activos Cat. 1], 
IRB.DEPRECIACION_ACTIVOS_FIJOS2 [Gastos de depreciación de activos Cat. 2],
IRB.DEPRECIACION_ACTIVOS_FIJOS3 [Gastos de depreciación de activos Cat. 3],
IRB.REPARACION_ACTIVOS_FIJOS1 [Reparación de activos Cat 1],
IRB.REPARACION_ACTIVOS_FIJOS2_3 [Reparación de activos Cat 2 y Cat 3],
IRB.MANTENIMIENTO_ACTIVOS [Mantenimiento de los activos], 
IRB.AMORTIZACION_BIENES_INTANGIBLES [Amortización de bienes intangibles],
IRB.TOTAL_GASTOS_ACTIVOS_FIJOS [Total de gastos de activos fijos],
IRB.RELACIONES_PUBLICAS [Gastos de Relaciones publicas],
IRB.PUBLICIDAD [Gastos de Publicidad],
IRB.VIAJES [Gastos de Viajes],
IRB.PROMOCIONES [Gastos de Promociones],
IRB.REPRESENTACION [Otros gastos de representación], 
IRB.TOTAL_GATOS_REPRESENTACION [Total de gastos de representación],
IRB.PRIMAS_DE_SEGUROS [Gastos de primas de seguros], 
IRB.PROPORCION_ITBIS_OPERACIONES_EXENTAS [Proporción de ITBIS pagado en operaciones exentas],
IRB.DESTRUCCION_INVENTARIO [Destrucción de Costos Aut. DGII], 
IRB.TOTAL_DE_OTRAS_DEDUCCIONES_ADMITIDAS [Total de otras deducciones de Admitidas],
IRB.PRESTAMOS_CON_INST_FINANCIERAS_LOCALES [Prestamos por instituciones financieras locales], 
IRB.PRESTAMOS_ENTIDADES_EXTERIOR [Prestamos con entidades del exterior],
IRB.PRESTAMOS_CON_RELACIONADAS_LOCALES [Prestamos con entidades relacionadas locales],
IRB.PRESTAMOS_CON_INST_FINANCIERAS_EXTERIOR [Prestamos con entidades relacionadas del exterior], 
IRB.PRESTAMOS_CON_PERSONAS_FISICAS [Prestamos con personas físicas],
IRB.RETENCION_CHEQUES_TRANSFERENCIAS [Retención del 0.15 (Cheques y transferencia)],
IRB.OTROS_GASTOS_FINANCIEROS [Otros Gastos Financieros], 
IRB.TOTAL_GASTOS_FINANCIEROS [Total de Gastos Financieros],
IRB.PERDIDAS_ACTIVOS_DEPRECIABLES [Por perdidas en ventas de activos depreciables],
IRB.PERDIDAS_BIENES_CAPITAL [Por perdidas en ventas de bines de capital],
IRB.OTROS_GASTOS_EXTRAORDINARIOS [Otros Gastos Extraordinarios], 
IRB.TOTAL_GASTOS_EXTRAORDINARIOS [Total de  gastos extraordinarios],

CASE WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.AFP END [Aporte plan de pensiones],
CASE  WHEN IR1.TCU_PERIODO_DEC BETWEEN 20512 AND 201612 THEN IR1.SFS END [Pagos efectuados a la Seguridad Social]



/*IR1*/
FROM(
Select 
A.TCU_RUC_CUMPLIMIENTO, A.TCU_NUM_DECLARACION,A.TCU_DECLARACION_SUST,A.TCU_PERIODO_DEC,a.TCU_FEC_CUMPLIMIENTO,A.TCU_TIP_DECLARACION,A.TCU_TIP_DOCUMENTO,										
SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 009 THEN b.TDE_VAL_DECLARACION END ) INVENTARIO_INICIAL,
SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 010 THEN b.TDE_VAL_DECLARACION END ) COMPRAS_LOCALES
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 011 THEN b.TDE_VAL_DECLARACION END ) COMPRAS_EXTERIOR
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 012 THEN b.TDE_VAL_DECLARACION END ) INVENTARIO_FINAL
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 013 THEN b.TDE_VAL_DECLARACION END ) COSTO_VENTA
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 014 THEN b.TDE_VAL_DECLARACION END ) FACTURA_ELECTRICAS
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 015 THEN b.TDE_VAL_DECLARACION END ) FACTURA_TELEFONICA
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 016 THEN b.TDE_VAL_DECLARACION END ) ARRENDAMIENTO
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 017 THEN b.TDE_VAL_DECLARACION END ) GASTOS_COMBUSTIBLE
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 019 THEN b.TDE_VAL_DECLARACION END ) SUELDOS_SALARIOS
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 020 THEN b.TDE_VAL_DECLARACION END ) AFP
,SUM (DISTINCT  CASE WHEN a.TCU_PERIODO_DEC between 201512 AND 201612 and b.TDE_COD_ITEM = 021 THEN b.TDE_VAL_DECLARACION END ) SFS


from Cruces_PlanMas..TAB_CUMPLIMIENTOS a 
left join Cruces_PlanMas..TAB_DECLARACIONES b on a.TCU_NUM_DECLARACION = b.TDE_TCU_NUM_DECLARACION 
and b.TDE_COD_ITEM in (009,010,011,012,013,019,020,021,016,014,015,017)
and b.TDE_IND_NORMALIZA = 0
where a.TCU_TFO_COD_FORMULARIO = 'IR1'
--and a.TCU_TIP_DECLARACION = 1
--AND A.TCU_RUC_CUMPLIMIENTO='04701007561'
--and a.TCU_TIP_DOCUMENTO IN (1,4)

GROUP BY a.TCU_RUC_CUMPLIMIENTO,a.TCU_PERIODO_DEC, a.TCU_NUM_DECLARACION, TCU_DECLARACION_SUST, TCU_TIP_DOCUMENTO,TCU_TIP_DECLARACION, a.TCU_FEC_CUMPLIMIENTO
)IR1

LEFT JOIN

(SELECT

a.TCU_RUC_CUMPLIMIENTO,
a.TCU_PERIODO_DEC,
a.TCU_NUM_DECLARACION,
SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 016 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 015 THEN D.TDA_VAL_DECLARACION END ) INVENTARIO_INICIAL,

 SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 017 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 016 THEN D.TDA_VAL_DECLARACION END ) COMPRAS_LOCALES

 ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 018 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 017 THEN D.TDA_VAL_DECLARACION END ) COMPRAS_EXTERIOR

  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 019 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 018 THEN D.TDA_VAL_DECLARACION END ) ITBIS_LLEVADO_AL_COSTO

   ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 020 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 019 THEN D.TDA_VAL_DECLARACION END ) INVENTARIO_FINAL

    ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 021 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 020 THEN D.TDA_VAL_DECLARACION END ) COSTO_VENTA	   	  
 
    ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 022 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 021 THEN D.TDA_VAL_DECLARACION END ) SUELDO_SALARIOS

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 023 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 022 THEN D.TDA_VAL_DECLARACION END ) RETRIBUCIONES_COMPLEMENTARIAS

     ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 024 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 023 THEN D.TDA_VAL_DECLARACION END ) SEGUROS

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 025 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 024 THEN D.TDA_VAL_DECLARACION END ) APORTE_TSS

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 026 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 025 THEN D.TDA_VAL_DECLARACION END ) APORTE_INFOTEP

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 027 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 026 THEN D.TDA_VAL_DECLARACION END ) OTROS_GASTOS_PERSONAL

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 028 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 027 THEN D.TDA_VAL_DECLARACION END ) TOTAL_GASTOS_PERSONAL

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 029 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 028 THEN D.TDA_VAL_DECLARACION END ) _HONORARIOS_SERVICIOS_PROFESIONALES

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 030 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 029 THEN D.TDA_VAL_DECLARACION END ) HONORARIOS_SERVICIOS_EXTERIOR_392

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 031 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 030 THEN D.TDA_VAL_DECLARACION END ) HONORARIOS_SERVICIOS_EXTERIOR_PFJ

      ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 032 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 031 THEN D.TDA_VAL_DECLARACION END ) FACTURAS_ELECTRICAS

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 033 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 032 THEN D.TDA_VAL_DECLARACION END ) FACTURAS_TELEFONICAS

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 034 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 033 THEN D.TDA_VAL_DECLARACION END ) SUMINISTRO_COMBUSTIBLE

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 035 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 034 THEN D.TDA_VAL_DECLARACION END ) SEGURIDAD_MESAJERIA_TRANSPORTE

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 036 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 035 THEN D.TDA_VAL_DECLARACION END ) OTROS_TRABAJOS_SUMINISTRO_SERVICIOS

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 037 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 036 THEN D.TDA_VAL_DECLARACION END ) TOTAL_TRABAJO_SUMINISTRO_SERVICIO

        ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 038 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 037 THEN D.TDA_VAL_DECLARACION END ) ARRENDAMIENTO

       ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 039 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 038 THEN D.TDA_VAL_DECLARACION END ) DEPRECIACION_ACTIVOS_FIJOS1

        ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 040 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 039 THEN D.TDA_VAL_DECLARACION END ) DEPRECIACION_ACTIVOS_FIJOS2

         ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 041 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 040 THEN D.TDA_VAL_DECLARACION END ) DEPRECIACION_ACTIVOS_FIJOS3

        ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 042 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 041 THEN D.TDA_VAL_DECLARACION END )REPARACION_ACTIVOS_FIJOS1

         ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 043 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 042 THEN D.TDA_VAL_DECLARACION END )REPARACION_ACTIVOS_FIJOS2_3

          ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  = 044 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 043 THEN D.TDA_VAL_DECLARACION END ) MANTENIMIENTO_ACTIVOS

           ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =045 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 044 THEN D.TDA_VAL_DECLARACION END ) AMORTIZACION_BIENES_INTANGIBLES

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =046 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 045 THEN D.TDA_VAL_DECLARACION END ) TOTAL_GASTOS_ACTIVOS_FIJOS

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =047 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 046 THEN D.TDA_VAL_DECLARACION END ) RELACIONES_PUBLICAS

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =048 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 047 THEN D.TDA_VAL_DECLARACION END ) PUBLICIDAD

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =049 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 048 THEN D.TDA_VAL_DECLARACION END ) VIAJES

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =050 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 049 THEN D.TDA_VAL_DECLARACION END ) PROMOCIONES

            ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =051 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 050 THEN D.TDA_VAL_DECLARACION END ) REPRESENTACION

             ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =052 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 051 THEN D.TDA_VAL_DECLARACION END ) TOTAL_GATOS_REPRESENTACION

              ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =053 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 052 THEN D.TDA_VAL_DECLARACION END ) PRIMAS_DE_SEGUROS

                ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =054 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 053 THEN D.TDA_VAL_DECLARACION END ) PROPORCION_ITBIS_OPERACIONES_EXENTAS

               ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =055 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 054 THEN D.TDA_VAL_DECLARACION END ) DESTRUCCION_INVENTARIO

               ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM  =056 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 055 THEN D.TDA_VAL_DECLARACION END ) TOTAL_DE_OTRAS_DEDUCCIONES_ADMITIDAS

                ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =057 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 056 THEN D.TDA_VAL_DECLARACION END ) PRESTAMOS_CON_INST_FINANCIERAS_LOCALES

                 ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =058 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 057 THEN D.TDA_VAL_DECLARACION END ) PRESTAMOS_ENTIDADES_EXTERIOR

                 ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =059 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 058 THEN D.TDA_VAL_DECLARACION END ) PRESTAMOS_CON_RELACIONADAS_LOCALES

                 ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =060 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 059 THEN D.TDA_VAL_DECLARACION END ) PRESTAMOS_CON_INST_FINANCIERAS_EXTERIOR

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =061 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 060 THEN D.TDA_VAL_DECLARACION END ) PRESTAMOS_CON_PERSONAS_FISICAS

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =062 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 061 THEN D.TDA_VAL_DECLARACION END ) RETENCION_CHEQUES_TRANSFERENCIAS

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =063 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 062 THEN D.TDA_VAL_DECLARACION END ) OTROS_GASTOS_FINANCIEROS

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =064 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 063 THEN D.TDA_VAL_DECLARACION END ) TOTAL_GASTOS_FINANCIEROS

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =065 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 064 THEN D.TDA_VAL_DECLARACION END ) PERDIDAS_ACTIVOS_DEPRECIABLES

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =066 THEN D.TDA_VAL_DECLARACION END ) PERDIDAS_BIENES_CAPITAL 

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =067 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 065 THEN D.TDA_VAL_DECLARACION END ) OTROS_GASTOS_EXTRAORDINARIOS

                  ,SUM (DISTINCT CASE WHEN a.TCU_PERIODO_DEC =201712 and d.TDA_COD_ITEM =068 THEN D.TDA_VAL_DECLARACION
 WHEN a.TCU_PERIODO_DEC >201712 and d.TDA_COD_ITEM  = 066 THEN D.TDA_VAL_DECLARACION END ) TOTAL_GASTOS_EXTRAORDINARIOS
             
 


from Cruces_PlanMas..TAB_CUMPLIMIENTOS a  ---508,266   19/06/2020----
left join Cruces_PlanMas..TAB_NUM_DEC_AUT c  on a.TCU_NUM_DECLARACION = c.NDA_NUM_PRE  and c.NDA_TFO_COD_FORMULARIO = 'IRB'
left join Cruces_PlanMas..TAB_DECLARACIONES_ANEXOS d ON C.NDA_TCU_NUM_DECLARACION = D.TDA_TCU_NUM_DECLARACION AND D.TDA_TDP_TFO_COD_ANEXO ='IRB'and D.TDA_IND_NORMALIZA=0
where a.TCU_TFO_COD_FORMULARIO ='IR1'

--and a.TCU_PERIODO_DEC  = 201712
								

												
GROUP BY a.TCU_RUC_CUMPLIMIENTO, a.TCU_PERIODO_DEC, a.TCU_NUM_DECLARACION)IRB

 ON IR1.TCU_RUC_CUMPLIMIENTO= IRB.TCU_RUC_CUMPLIMIENTO AND IR1.TCU_PERIODO_DEC=IRB.TCU_PERIODO_DEC AND IRB.TCU_NUM_DECLARACION=IR1.TCU_NUM_DECLARACION


 LEFT JOIN (SELECT D.TED_RGE_RUC,D.TED_PER_REFERE,D.TED_NRO_DEC,CASE WHEN D.TED_COD_TERMINAL='INTERNET' THEN 'OFV' ELSE 'ADM' END VIA_DECLARACION
 FROM Cruces_PlanMas..TAB_EFETUAR_DEC D)  D ON IR1.TCU_NUM_DECLARACION=D.TED_NRO_DEC
 --WHERE ir1.TCU_PERIODO_DEC  between '201512' and '202112'
 --AND cast(IR1.TCU_FEC_CUMPLIMIENTO as date)<='2022-03-1
